[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
sl_trading = "EAJ7QiDXgXH31m57RhDFMHTkBrDzxrFpcN8xUkPUqHLi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/work-files/coding/git-files/sol-dev-key-pair/LincR97JvGscu9DDwLLUuZK196ENLSyF9Xc3Ehmhm2Y.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
